LOAD DATA LOCAL INFILE '~/data/Seller.del' INTO TABLE Seller FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE '~/data/Bidder.del' INTO TABLE Bidder FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE '~/data/Item.del' INTO TABLE Item FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE '~/data/ItemCategory.del' INTO TABLE ItemCategory FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE '~/data/ItemBid.del' INTO TABLE ItemBid FIELDS TERMINATED BY '|*|';
